models/Catalog.php
<?php
/**
 * Created by PhpStorm.
 * User: Алексей
 * Date: 12.01.2016
 * Time: 15:17
 */
namespace app\models;
use Yii;
use yii\base\Object;
use yii\db\ActiveRecord;

use creocoder\nestedsets\NestedSetsBehavior;
use yii\helpers\ArrayHelper;

class Catalog extends ActiveRecord
{
    const TYPE_GROUP = 1;
    const TYPE_PART = 0;

    public function behaviors() {
        return [
            'tree' => [
                'class' => NestedSetsBehavior::className(),
                'treeAttribute' => 'tree',
                // 'leftAttribute' => 'lft',
                // 'rightAttribute' => 'rgt',
                // 'depthAttribute' => 'depth',
            ],
        ];
    }

	public function transactions()
	{
		return [
			self::SCENARIO_DEFAULT => self::OP_ALL,
		];
	}

    public static function find()
    {
        return new CatalogQuery(get_called_class());
    }

    public  static function showChilds($leaves, $depth,$idsChecked=[])
    {
        $result = [];

        $go = false;
        foreach($leaves as $leave)
        {
            if (($leave->depth == $depth))
            {
                $go = true;
            }
        }
        if ($go == false)
            return;

        foreach ($leaves as $leave) {
                if (($leave->depth == $depth)) {
                    $dataNode = [];
                    if ($leave->node_type <> 0)
                    {
                        $dataNode['node_type']=$leave->node_type;
                        $dataNode['icon']='glyphicon glyphicon-book';
                    }
                    else
                    {
                        $dataNode['icon']='glyphicon glyphicon-folder-open';
                        $dataNode['state']['expanded'] = true;
                    }

                    if(in_array($leave->id,$idsChecked))
                        $dataNode['state']['checked'] = true;

                    $dataNode['text']=$leave->name;
                    $dataNode['id']=$leave->id;

                    $dataNode['nodes'] = self::showChilds($leaves, $leave->id,$idsChecked);

                    $result[] = (object)$dataNode;
                }
        }

        return $result;
    }
    public static function showTree($leaves,$idsChecked=[])
    {
        $result = [];
        foreach($leaves as $leave)
        {
            if($leave->depth == 0)
                $result[] = (object)['id'=>$leave->id,'text'=>$leave->name,'nodes'=>self::showChilds($leaves, $leave->id,$idsChecked)];
        }
        return $result;
    }

    public static function ShowChildsFix($root)
    {
        if (!is_object($root))
            return $arr = [];
        $childs = $root->children(1)->all();
        $arr = [];
        $childs = self::sortTree($childs);
        foreach ($childs as $child)
        {
            if (Yii::$app->user->identity->role_id == 2)
            {
                if(AccessUserGroupMaterial::find()->where(['id_user' => Yii::$app->user->identity->id, 'id_group_material' => $child->id])->one()
                    ||
                    $child->node_type == 0) {
                    $obj = [
                        'text' => $child->name,
                        'id' => $child->id,
                        'node_type' => $child->node_type
                    ];

                    if ($child->node_type == 0) {
                        $obj['icon'] = 'glyphicon glyphicon-folder-open';
                        $obj['state']['expanded'] = true;
                    } else if ($child->node_type == 1) {
                        $obj['icon'] = 'glyphicon glyphicon-book';
                    }

                    $obj['nodes'] = self::ShowChildsFix($child);
                    $arr[] = (object)$obj;
                }
            }
            else{
                $obj = [
                    'text' => $child->name,
                    'id' => $child->id,
                    'node_type' => $child->node_type
                ];

                if ($child->node_type == 0) {
                    $obj['icon'] = 'glyphicon glyphicon-folder-open';
                    $obj['state']['expanded'] = true;
                } else if ($child->node_type == 1) {
                    $obj['icon'] = 'glyphicon glyphicon-book';
                }

                $obj['nodes'] = self::ShowChildsFix($child);
                $arr[] = (object)$obj;
            }
        }
        return $arr;
    }

    public static function ShowTreeFix()
    {
        $result = Catalog::find()->roots()->all();
        $leaves = [];
        $obj = [
            'text'=>$result[0]->name,
            'id'=>$result[0]->id,
            'nodes'=>$obj['nodes'] = self::ShowChildsFix($result[0])
        ];
        $leaves[] = (object)$obj;
        return $leaves;
    }

    public static function sortTree($leaves)
    {
        $sorted = false;
        $length = count($leaves) - 1;
        //
        while ($sorted == false)
        {
            $sorted = true;
            for ($i = 0; $i < $length; $i++)
            {
                if ($leaves[$i]->name > $leaves[$i+1]->name)
                {
                    $k = $leaves[$i];
                    $leaves[$i] = $leaves[$i+1];
                    $leaves[$i+1] = $k;
                    $sorted = false;
                }
            }
        }
        return $leaves;
    }

    //-------------------------------------------
    // functions of tree for access page

    public static function ShowChildsForAccessGroupsMaterial($root,$idsChecked)
    {
        $childs = $root->children(1)->all();
        $arr = [];
        $childs = self::sortTree($childs);
        foreach ($childs as $child)
        {
            $obj = [
                'text'=>$child->name,
                'id'=>$child->id,
                'node_type'=>$child->node_type
            ];

            if ($child->node_type == 0)
            {
                $obj['icon'] = 'glyphicon glyphicon-folder-open';
                $obj['state']['expanded'] = true;
            }
            else if ($child->node_type == 1)
            {
                $obj['icon'] = 'glyphicon glyphicon-book';
            }

            if(in_array($child->id,$idsChecked))
                $obj['state']['checked'] = true;

            $obj['nodes'] = self::ShowChildsForAccessGroupsMaterial($child,$idsChecked);
            $arr[] = (object)$obj;
        }
        return $arr;
    }

    public static function ShowTreeForAccessGroupsMaterialAndSelected($idsChecked=[])
    {
        $result = Catalog::find()->roots()->all();
        $leaves = [];
        $obj = [
            'text'=>$result[0]->name,
            'id'=>$result[0]->id,
            'nodes'=>$obj['nodes'] = self::ShowChildsForAccessGroupsMaterial($result[0],$idsChecked)
        ];
        $leaves[] = (object)$obj;
        return $leaves;
    }

    // ------------------------------------------


    public static function getTreeDataForAccessGroups() {

        $leaves = Catalog::find()->all();

        return self::showTree($leaves);
    }

    public static function getTreeDataForAccessGroupsAndSelected($idsChecked = []) {

        $leaves = Catalog::find()->all();

        return self::showTree($leaves,$idsChecked);
    }

    public static function checkAndGetIdsOfGroupElements($rawIds=[]) {

        $rows = self::find()->where(['node_type'=>self::TYPE_GROUP,'id'=>$rawIds])->asArray()->all();

        $rowsData = ArrayHelper::map($rows,'id','id');
        return array_keys($rowsData);
    }

}

controllers/CatalogController.php
<?php

namespace app\controllers;
use app\models\AccessUserGroupMaterial;
use app\models\BaseMaterial;
use app\models\Catalog;
use app\models\CharacteristicGroup;
use app\models\CharacteristicGroupTemp;
use app\models\ExcelReport;
use app\models\GroupSectionForm;
use app\models\SectionForm;
use roopz\imap\Exception;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use Yii;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;

class CatalogController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    public function actionIndex()
    {
        $section = new SectionForm();
        $leaves = Catalog::ShowTreeFix();
        $leaves = json_encode($leaves);
        if (Yii::$app->user->identity->role_id == 2)
        {
            return $this->render('userindex', [
                'leaves' => $leaves,
                'section' => $section,
            ]);
        }
        else
        {
            return $this->render('index', [
                'leaves' => $leaves,
                'section' => $section,
            ]);
        }
    }
    /*
     * Создание каталога
     */
    public function actionCreate()
    {
        $model = new SectionForm();
        $id = ($_GET['id']);
        if ($model->load(Yii::$app->request->post()))
        {
            $root = Catalog::findOne(['id' => $id]);
            $subsection = new Catalog(['name' => $model->name]);
            $subsection->appendTo($root);
            return $this->redirect(['catalog/index']);
        }

        if ($id)
        {
            if (($root = Catalog::findOne(['id' => $id])) &&($root->node_type == 0))
            {
                return $this->render('create', [
                    'id' => $id,
                    'model' => $model
                ]);
            }
            else
            {
                $message = 'Выберите раздел для создания подраздела, а не группу';
                /*return $this->render('create', [
                    'message' => $message,
                    'model' => $model
                ])1*/;
            }
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }
    /*
     * Редактирование каталога
     */
    public function actionEdit()
    {
        $model = new SectionForm();
        $id = ($_GET['id']);
        if ($model->load(Yii::$app->request->post()) )
        {
            $record = Catalog::findOne(['id' => $id]);
//            var_dump($record);
//            exit();
            $record->name = $model->name;
            $record->save();
            return $this->redirect(['catalog/index']);
        }
        if ($modelMenu = Catalog::findOne(['id' => $id]))
        {
            $model->id = $modelMenu->id;
            $model->name = $modelMenu->name;
            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }
    /*
     * Создание группы
     */
    public function actionGroup()
    {
        $id = ($_GET['id']);

        $model = new GroupSectionForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $root = Catalog::findOne(['id' => $id]);
            $group = new Catalog(['name' => $model->name, 'table_name' => $model->table_name, 'node_type' => 1]);
            $group->table_name = preg_replace('/[^a-zA-Z]/', "", Yii::$app->security->generateRandomString());
            $group->appendTo($root);

            // Копируем характеристики

            $charGroupTemp = CharacteristicGroupTemp::findAll(['id_user' => Yii::$app->user->identity->id]);
            foreach ($charGroupTemp as $item)
            {
                $newGroup = new CharacteristicGroup();
                $newGroup->name = $item->name;
                $newGroup->label = preg_replace('/[^a-zA-Z]/', "", Yii::$app->security->generateRandomString());
                $newGroup->type_value = $item->type_value;
                $newGroup->is_required = $item->is_required;
                $newGroup->id_group = $group->id;
                $newGroup->save();
            }
            // -------------

            // Создаем таблицу
            BaseMaterial::createTable($group);

            // Удаляем темп
            CharacteristicGroupTemp::deleteAll(['id_user' => Yii::$app->user->identity->id]);
            // -------------
            return $this->redirect(['catalog/index']);
        }
        if (($root = Catalog::findOne(['id' => $id])) &&($root->node_type == 0))
        {
            $query = CharacteristicGroupTemp::find()->where(['id_user' => Yii::$app->user->identity->id]);
            $attributesModel = new ActiveDataProvider([
                'query' => $query
            ]);
            $model->id = $id;
            return $this->render('creategroup', [
                'attributesModel' => $attributesModel,
                'model' => $model
            ]);
        }
//        return $this->render('creategroup', [
//            'model' => $model
//        ]);
    }

    /*
     * Редактирование группы
     */
    public function actionEditgroup()
    {
        $model = new GroupSectionForm();
        $id = ($_GET['id']);
        $query = CharacteristicGroup::find()->where(['id_group' => $id]);
        $attributesModel = new ActiveDataProvider([
            'query' => $query
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $group = Catalog::findOne(['id' => $id]);
            $group->name = $model->name;
            $group->save();
            BaseMaterial::updateTable($group);
            return $this->redirect(['catalog/index']);
        }
        if (($root = Catalog::findOne(['id' => $id])) &&($root->node_type == 1))
        {
            $model->id = $id;
            $model->name = $root->name;
            return $this->render('editgroup', [
                'model' => $model,
                'attributesModel' => $attributesModel
            ]);
        }
        return $this->redirect(['catalog/index']);
    }


    //---------------------------------------------

//    public function actionDeleteAllCatalog() {
//
//        $allGroups = Catalog::findAll(['node_type'=>1]);
//        if(is_array($allGroups)) {
//
//
//
//            foreach($allGroups as $curGroup) {
//
//                if(!empty($curGroup->table_name) && !is_null($curGroup->table_name) && Yii::$app->db->schema->getTableSchema($curGroup->table_name, true) !== null) {
//                        $dd= Yii::$app->db->createCommand()->dropTable($curGroup->table_name)->execute();
//                }
//                CharacteristicGroup::deleteAll(['id_group'=>$curGroup->id]);
//                AccessUserGroupMaterial::deleteAll(['id_group_material'=>$curGroup->id]);
//                ExcelReport::deleteAll(['catalog_id'=>$curGroup->id]);
//
//            }
//
//            BaseMaterial::deleteAll();
//
//
//        }
//
//        Catalog::deleteAll('id<>:id',[':id'=>1]);
//
//
//    }

    public function actionDeletegroup()
    {
        $id = Yii::$app->request->get('id');
        $group = Catalog::findOne(['id' => $id]);
        if ($group->node_type == 0)
        {
            throw new NotFoundHttpException();
        }
        else
        {
            try{
                $result = BaseMaterial::deleteTableWithRows($group);
            }
            catch(Exception $e)
            {
                //Надо записать в лог ошибку я думаю
            }
            if ($result == 0)
                throw new NotFoundHttpException();
            $group->deleteWithChildren();
        }
        $urlToRedirect = Url::toRoute('catalog/index');
        return $this->redirect($urlToRedirect);
    }


    public function actionDeletesection()
    {
        $id = Yii::$app->request->get('id');

        $root = Catalog::findOne(['id' => $id]);
        $leaves = $root->leaves()->all();
        BaseMaterial::deleteRecursiveGroups($leaves);
        $root->deleteWithChildren();

        $urlToRedirect = Url::toRoute('catalog/index');
        return $this->redirect($urlToRedirect);
    }
    //---------------------------------------------------------------------------------------

    //---------------------------------------------------------------------------------------
    // сверка дат
    public function actionReviseDates() {
        if (Yii::$app->user->identity->role_id == '2')
            throw new \yii\web\ForbiddenHttpException('У вас нет доступа к этому разделу');
        $model = new BaseMaterial();
        $model->load(Yii::$app->request->get());
        return $this->render('reviseDates',['model'=>$model,'filter'=>$model]);

    }

    public function actionRefreshReviseDataOfMaterial() {

        $result = ['success'=>true,'message'=>'Дата сверки обновлена'];

        $id = Yii::$app->request->get('id');

        $customer = BaseMaterial::findOne($id);
        if($customer) {
            $customer->date_verify = date('Y-m-d H:i:s');
            $customer->update();

            $result['date'] = date('d.m.Y',strtotime($customer->date_verify));
        } else {
            $result['success'] = false;
            $result['message'] = 'Материал не найден';
        }

        return json_encode($result);
    }
}

views/catalog/create.php
<?php
/**
 * Created by PhpStorm.
 * User: Алексей
 * Date: 14.01.2016
 * Time: 19:00
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Создать раздел';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="menu-form">
<!--    --><?// echo $message?>
    <? $form = ActiveForm::begin(); ?>

    <div class="hidden">
        <?
            $model->id = $id;
            echo $form->field($model, 'id');
        ?>
    </div>
        <?= $form->field($model, 'name') ?>
    <?= Html::submitButton('Добавить раздел', ['class' => 'btn btn-success']) ?>
    <?php ActiveForm::end(); ?>
</div>

views/catalog/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: Алексей
 * Date: 14.01.2016
 * Time: 19:00
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Редактировать каталог';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="menu-form">
    <? echo $message?>
    <? $form = ActiveForm::begin(); ?>

    <div class="hidden">
        <?

            echo $form->field($model, 'id');
        ?>
    </div>
        <?= $form->field($model, 'name') ?>
    <?= Html::submitButton('Изменить название', ['class' => 'btn btn-success']) ?>
    <?php ActiveForm::end(); ?>
</div>

views/catalog/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\bootstrap\Modal;
/* @var $this yii\web\View */

$this->title = 'Каталог разделов';
$this->params['breadcrumbs'][] = $this->title;

//ссылка (переход при дабл клике на страницу группы)
$urlIndex = Url::toRoute(['/basematerial/index']);

//Действия с excel
$urlUpload = Url::toRoute(['/basematerial/import']);
$url = Url::toRoute(['/basematerial/excel']);

//Действия с группами
$urlCreate = Url::toRoute(['/catalog/create']);
$urlEdit = Url::toRoute(['/catalog/edit']);
$urlDelete = Url::toRoute(['/catalog/deletesection']);

//Действия с разделами
$urlGroup = Url::toRoute(['/catalog/group']);
$urlEditGroup = Url::toRoute(['/catalog/editgroup']);
$urlDeleteGroup = Url::toRoute(['/catalog/deletegroup']);

$script = <<< JS
    //Куки имени раздела если вдруг перешел из страницы создания/редактирования раздела
    setCookie('group-name', '');

    //Действия с группами
    $('#section').click(function(){
        var x = $('.node-selected');
        var id = $(x).attr('id');
        var node_type = $(x).attr('node_type');
        console.log('id:',id,' node_type:',node_type);
        if ((node_type == 0 || node_type == undefined) && (id))
        {
            var url = '{$urlCreate}'+'?id='+id;
            $(location).attr('href',url);
        }
        else
        {
            alert('Выберите раздел для добавления подраздела');
        }
    });
    $('#edit').click(function(){
        var x = $('.node-selected');
        var id = $(x).attr('id');
        var node_type = $(x).attr('node_type');
        console.log('id:',id,' node_type:',node_type);
        if ((id) && (node_type == 0 || node_type == undefined))
        {
            var url = '{$urlEdit}'+'?id='+id;
            $(location).attr('href',url);
        }
        else
        {
            alert('Выберите раздел для редактирования');
        }
    });
    $('#delete').click(function(){
        var x = $('.node-selected');
        var id = $(x).attr('id');
        var node_type = $(x).attr('node_type');
        console.log('id:',id,' node_type:',node_type);
        if ((id) && (node_type == 0 || node_type == undefined))
        {
            var url = '{$urlDelete}'+'?id='+id;
            $(location).attr('href',url);
        }
        else
        {
            alert('Выберите раздел для редактирования');
        }
    });

    //Действия с разделами
    $('#group').click(function(){
        var x = $('.node-selected');
        var id = $(x).attr('id');
        var node_type = $(x).attr('node_type');
        console.log('id:',id,' node_type:',node_type);
        if ((id) && (node_type == 0 || node_type == undefined))
        {
            var url = '{$urlGroup}'+'?id='+id;
            $(location).attr('href',url);
        }
        else
        {
            alert('Выберите раздел для добавления группы');
        }
    });
    $('#editgroup').click(function(){
        var x = $('.node-selected');
        var id = $(x).attr('id');
        var node_type = $(x).attr('node_type');
        console.log('id:',id,' node_type:',node_type);
        if ((id) && (node_type == 1))
        {
            var url = '{$urlEditGroup}'+'?id='+id;
            $(location).attr('href', url);
        }
        else
        {
            alert('Выберите группу для редактирования');
        }
    });
    $('#deletegroup').click(function(){
        var x = $('.node-selected');
        var id = $(x).attr('id');
        var node_type = $(x).attr('node_type');
        console.log('id:',id,' node_type:',node_type);
        if ((id) && (node_type == 1))
        {
            var url = '{$urlDeleteGroup}'+'?id='+id;
            $(location).attr('href', url);
        }
        else
        {
            alert('Выберите группу для редактирования');
        }
    });

    //Действия с excel
    $("#outputtoxml").click(function(){
        var node = $(".node-selected");
        var id = node.attr("id");
        var node_type = node.attr("node_type");
        console.log(id,node_type);
        if ((id) && (node_type == 1))
        {
            var url = '{$url}'+'?id='+id;
            $(location).attr('href', url);
        }
        else
        {
            alert('Выберите группу');
        }
    });
    $("#inputfromxml").click(function(){
        var node = $(".node-selected");
        var id = node.attr("id");
        var node_type = node.attr("node_type");
        if ((id) && (node_type == 1))
        {
            var url = '{$urlUpload}'+'?id='+id;
            $(location).attr('href', url);
        }
        else
        {
            alert('Выберите группу');
        }
    });

    //Отображение дерева
    $('#tree').treeview({data: $leaves,renderCustom:function(options,treeItem,node){
         if($(treeItem).hasClass('group-color')){
            $(treeItem).attr('title','Нажмите 2 раза для просмотра материала.')
        }

    }});

    //Переход при дабл клике на страницу группы
    $('#tree').on('dblclick','.group-color',function(event){
        var id = $(this).attr('id');
        var url = '{$urlIndex}'+'?id='+id;
        $(location).attr('href', url);
    });

JS;
$this->registerJs($script, yii\web\View::POS_READY);
?>
<div class="col-xs-2"><h4>Каталог разделов</h4></div>
<div class="col-xs-10">
    <nav class="navbar">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Разделы
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#" id="section">Создать раздел</a></li>
                        <li><a href="#" id="edit">Редактировать раздел</a></li>
                        <li><a href="#" id="delete">Удалить раздел</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Группы
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#" id="group">Создать группу</a></li>
                        <li><a href="#" id="editgroup">Редактировать группу</a></li>
                        <li><a href="#" id="deletegroup">Удалить группу</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Excel
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#" id="outputtoxml">Экспорт в Excel</a></li>
                        <li><a href="#" id="inputfromxml">Импорт из Excel</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</div>
<div class="col-xs-12" id="tree">
</div>

views/catalog/reviseDates.php
<?php

use yii\grid as yiiGrid;
use yii\jui\DatePicker;

$this->title = 'Сверка дат';
$this->params['breadcrumbs'][] = $this->title;
//yiiGrid\DataColumn::className();


$script = <<< JS
$(document).on('click', '.refresh-revise-data-material', function(e) {

    e.preventDefault();
    var address = $(e.target).closest('a').attr('href');

    console.log('click refresh');
    $.ajax({
       url: address,
       data: {id: $(e.target).closest('a').attr('data-id')},
       success: function(rawData) {
            var data = JSON.parse(rawData);
           //console.log('success refresh date verify '+data.message);
           if(data.success) {
                $(e.target).closest('tr').find('.date-verify-column').text(data.date);
           }

       }
    });

    return false;
});
JS;
$this->registerJs($script, yii\web\View::POS_READY);

?>


<?php \yii\widgets\Pjax::begin(); ?>

<?= yiiGrid\GridView::widget([
    'id'=>'base-material-grid-view',
    'dataProvider' 	=> $model->search(),
    'filterModel'  	=> $model,
    //'layout'  		=> "{pager}\n{items}\n{pager}",
    'columns' => [
        [
            'label'=>'Наименование',
            'attribute'=>'name',
            'filter'=>false
        ],

        [
            'label'=>'Дата сверки',
            'format' => 'date',
            'attribute'=>'date_verify',
            'filter' => DatePicker::widget(
                    [
                        'model' => $model,
                        'attribute' => 'date_verify',
                        'options' => [
                            'class' => 'form-control'
                        ],
                        'clientOptions' => [
                            'dateFormat' => 'dd.mm.yy',
                        ]
                    ]
                ),
            'contentOptions' => ['style' => 'width:160px;','class'=>'date-verify-column'],
            'headerOptions' => ['style' => 'width:160px;'],
        ],

        [
            'label'=>'Источник',
            'attribute'=>'source',
            'filter'=>false
        ],

        [
            'label'=>'Шифр',
            'attribute'=>'code',
            'filter'=>false
        ],

        [
            'label'=>'Комментарий',
            'attribute'=>'note',
            'filter'=>false
        ],

        [
            'class' => \yii\grid\ActionColumn::className(),
            'buttons'=>[
                'view'=>function ($url, $model) {
                        $customurl=Yii::$app->getUrlManager()->createUrl(['/catalog/refresh-revise-data-of-material','id'=>$model->id]); //$model->id для AR
                        return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-refresh"></span>', $customurl,
                            ['title' => 'Обновить дату сверки', 'data-pjax' => '0','class'=>'refresh-revise-data-material','data-id'=>$model->id]);
                    }
            ],
            'template'=>'{view}',
        ]

        /*[
            'attribute' => 'created_at',
            'value' => function ($model) {
                if (extension_loaded('intl')) {
                    return Yii::t('user', '{0, date, MMMM dd, YYYY HH:mm}', [$model->created_at]);
                } else {
                    return date('Y-m-d G:i:s', $model->created_at);
                }
            },
            'filter' => DatePicker::widget([
                'model'      => $searchModel,
                'attribute'  => 'created_at',
                'dateFormat' => 'php:Y-m-d',
                'options' => [
                    'class' => 'form-control',
                ],
            ]),
        ],*/
//        [
//            'header' => Yii::t('user', 'Confirmation'),
//            'value' => function ($model) {
//                    if ($model->isConfirmed) {
//                        return '<div class="text-center"><span class="text-success">' . Yii::t('user', 'Confirmed') . '</span></div>';
//                    } else {
//                        return Html::a(Yii::t('user', 'Confirm'), ['confirm', 'id' => $model->id], [
//                            'class' => 'btn btn-xs btn-success btn-block',
//                            'data-method' => 'post',
//                            'data-confirm' => Yii::t('user', 'Are you sure you want to confirm this user?'),
//                        ]);
//                    }
//                },
//            'format' => 'raw',
//            'visible' => Yii::$app->getModule('user')->enableConfirmation,
//        ],
//        [
//            'header' => Yii::t('user', 'Block status'),
//            'value' => function ($model) {
//                    if ($model->isBlocked) {
//                        return Html::a(Yii::t('user', 'Unblock'), ['block', 'id' => $model->id], [
//                            'class' => 'btn btn-xs btn-success btn-block',
//                            'data-method' => 'post',
//                            'data-confirm' => Yii::t('user', 'Are you sure you want to unblock this user?'),
//                        ]);
//                    } else {
//                        return Html::a(Yii::t('user', 'Block'), ['block', 'id' => $model->id], [
//                            'class' => 'btn btn-xs btn-danger btn-block',
//                            'data-method' => 'post',
//                            'data-confirm' => Yii::t('user', 'Are you sure you want to block this user?'),
//                        ]);
//                    }
//                },
//            'format' => 'raw',
//        ],
//        [
//            'class' => 'yii\grid\ActionColumn',
//            'template' => '{update} {delete}',
//        ],
    ],
]); ?>

<?php \yii\widgets\Pjax::end() ?>