controllers/BaseMaterialController.php
<?php

namespace app\controllers;

use app\models\AccessUserGroupMaterial;
use app\models\BaseMaterial;
use app\models\Catalog;
use app\models\CharacteristicGroup;
use app\models\DynamicMaterialFormSearch;
use app\models\ExcelReport;
use app\models\ImportFromExcel;
use app\models\ImportModel;
use Yii;
use app\models\BaseMaterial2;
use app\models\BaseMaterialSearch;
use yii\db\Query;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\DynamicFormMaterial;
use yii\base\DynamicModel;use yii\web\UploadedFile;
use PHPExcel;
use PHPExcel_Style_Alignment;

/**
 * BaseMaterialController implements the CRUD actions for BaseMaterial2 model.
 */
class BasematerialController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BaseMaterial2 models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BaseMaterialSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if ($id = Yii::$app->request->get('id'))
        {
            if (Yii::$app->user->identity->role_id == 1)
            {
                $group = Catalog::findOne(['id' => $id]);

                // берем все id из сгенерированной таблицы для поиска по base_material */
                $ids = BaseMaterial::getIds($group->table_name);

                // поиск по всем id из base_material
                $dataProvider = new ActiveDataProvider([
                    'query' => BaseMaterial::find()->where(['id' => $ids])
                ]);

                return $this->render('index', [
                    'group_name' => $group->name,
                    'group_id' => $id,
                    'dataProvider' => $dataProvider
                ]);
            }
            else
            {
                $group = Catalog::findOne(['id' => $id]);
                if (AccessUserGroupMaterial::findOne(['id_group_material' => $id, 'id_user' => Yii::$app->user->identity->id]))
                {
                    $model = new DynamicMaterialFormSearch();
                    $model->getSearchForm($id);
                    $group = Catalog::findOne(['id' => $id]);

                    // берем все id из сгенерированной таблицы для поиска по base_material */
                    $ids = BaseMaterial::getIds($group->table_name);

                    // поиск по всем id из base_material
                    if ($model->load(Yii::$app->request->post())){
                        $dataProvider = (new BaseMaterial())->filterSearch($model->columnSettings, $id);
                    }
                    else{
                        $dataProvider = new ActiveDataProvider([
                            'query' => BaseMaterial::find()->where(['id' => $ids])
                        ]);
                    }
                    return $this->render('userindex', [
                        'group_name' => $group->name,
                        'group_id' => $id,
                        'dataProvider' => $dataProvider,
                        'model' => $model
                    ]);
                }
                else
                {
                    $message = 'У вас нет доступа к этому разделу';
                    return $this->render('userindex', [
                        'message' => $message
                    ]);
                }
            }
        }
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAddreport()
    {
        $group_id = Yii::$app->request->get('group_id');
        $material_id = Yii::$app->request->get('id');
        $user_id = Yii::$app->user->identity->id;
        $materialName = BaseMaterial::findOne(['id' => $material_id])->name;
        if (Yii::$app->request->isAjax) {
            if (
                $row = (new Query())
                ->select('id')
                ->from(ExcelReport::tableName())
                ->where(['user_id' => $user_id, 'catalog_id' => $group_id, 'base_material_id' => $material_id])
                ->one()
            )
                return "<div class=\"alert alert-warning\">"."\"$materialName\" уже добавлен в отчет"."</div>";
            else
            {
                $row = (new Query())
                    ->createCommand()
                    ->insert(ExcelReport::tableName(), ['user_id' => $user_id, 'catalog_id' => $group_id, 'base_material_id' => $material_id])
                    ->execute();
                return "<div class=\"alert alert-success\">"."\"$materialName\" добавлен в отчет"."</div>";
            }
        }
    }

    public function actionGetreportexcel()
    {
        if (Yii::$app->request->isAjax)
        {
            if (ExcelReport::findOne(['user_id' => Yii::$app->user->identity->id]))
                return json_encode(Url::toRoute(['basematerial/report']));
            else
                return json_encode(false);
        }
    }

    public function actionReport()
    {
        if (Yii::$app->user->identity->role_id == 2) {
            BaseMaterial::getReports();
        }
    }

    public function actionImport()
    {
        $id = Yii::$app->request->get('id');
        $catalog = Catalog::findOne(['id' => $id]);
        $importModel = new ImportModel();
        $importModel->generateSettings($id);

        if ($importModel->load(Yii::$app->request->post()))
        {
            $importModel->file = UploadedFile::getInstance($importModel, 'file');
            if ($filename = $importModel->upload())
            {
                $import = new ImportFromExcel();
                $import->settings = $importModel->columnSettings;
                $import->id_group = $id;
                //$import->startRow = $importModel->startRow;
                $import->filename = $filename;
                $import->import();
                $url = Url::toRoute(['basematerial/index', 'id' => $id]);
                $this->redirect($url);
            }
        }
        return $this->render('import', [
            'catalog' => $catalog,
            'importModel' => $importModel,
        ]);
    }

// вывод в excel
    public function actionExcel()
    {
        /* Находим группу по id */
        $group_id = $_GET['id'];
        $group = Catalog::findOne(['id' => $group_id]);
        //получаем таблицу значений полей таблицы материала и характеристик
        $model = BaseMaterial::getModels($group);

        //установка ширины
        $xls = new \PHPExcel();
        $xls->setActiveSheetIndex(0);
        $xls->getActiveSheet()->getColumnDimension('A')->setWidth(30);
        $xls->getActiveSheet()->getColumnDimension('B')->setWidth(20);
        $xls->getActiveSheet()->getColumnDimension('C')->setWidth(22);
        $xls->getActiveSheet()->getColumnDimension('D')->setWidth(25);
        $xls->getActiveSheet()->getColumnDimension('E')->setWidth(22);

        //перевод строки
        foreach (range('A','Z') as $columnName){
            $xls->getActiveSheet()->getStyle($columnName)->getAlignment()->setWrapText(true);
            $xls->getActiveSheet()->getStyle($columnName)->getAlignment()->setHorizontal(
                PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
            $xls->getActiveSheet()->getStyle($columnName)->getAlignment()->setVertical(
                PHPExcel_Style_Alignment::VERTICAL_TOP);
        }
        //установка ширины
        foreach (range('F','Z') as $columnName){
            $xls->getActiveSheet()->getColumnDimension($columnName)->setWidth(15);
        }
        //импорт данных из массива $model
        $xls->getActiveSheet()->fromArray($model, null, 'A1');

        //Вывод excel файла
        $filename = 'ImportGroup_'.Yii::$app->user->identity->username.'_'.date('d-m-Y_H:i:s', time());
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename='.$filename.'.xls');
        header('Cache-Control: max-age=0');

        $writer = \PHPExcel_IOFactory::createWriter($xls, 'Excel5');
        $writer->save('php://output');
    }
    // Получаем характеристики по ajax

    public function actionModel()
    {
        if (Yii::$app->request->isAjax)
        {
            $group_id = $_GET['id'];
            $material_id = $_GET['material_id'];
            $group = Catalog::findOne(['id' => $group_id]);
            $columns = BaseMaterial::getColumnsAndLabels($group);
            $model = BaseMaterial::getModel($group, $material_id);
            return $this->renderAjax(
                '_detailview',
                [
                    'model' => $model,
                    'columns' => $columns
                ]
            );
        }
    }
    /**
     * Displays a single BaseMaterial2 model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new BaseMaterial2 model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
//    public function actionCreate()
//    {
//        $model = new BaseMaterial2();
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        } else {
//            return $this->render('create', [
//                'model' => $model,
//            ]);
//        }
//    }

    /**
     * Updates an existing BaseMaterial2 model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */

views/basematerial/_detailview.php
<?
/**
 * Created by PhpStorm.
 * User: Алексей
 * Date: 23.01.2016
 * Time: 15:33
 */
use yii\widgets\DetailView;

?>


<?= DetailView::widget([
    'model' => $model,
    'attributes' => $columns,
    'template' => '<tr><td style="width:25%">{label}</td><td>{value}</td></tr>'
]);
?>

views/basematerial/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BaseMaterial2 */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="base-material2-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date_verify')->textInput() ?>

    <?= $form->field($model, 'source')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'note')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/basematerial/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BaseMaterialSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="base-material2-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'date_verify') ?>

    <?= $form->field($model, 'source') ?>

    <?= $form->field($model, 'code') ?>

    <?php // echo $form->field($model, 'note') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/basematerial/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use yii\base\DynamicModel;

/* @var $this yii\web\View */
/* @var $model app\models\BaseMaterial2 */

$this->title = 'Создание материала';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="base-material2-update">
    <h3><?= Html::encode($this->title).": ".$modelForm->name; ?></h3>

    <?php $form = ActiveForm::begin(); ?>

    <?php

    foreach ($modelForm->attributes() as $curNameAttribute) {

        if(isset($modelForm->$curNameAttribute)) {

            $valueAttribute = $modelForm->$curNameAttribute;
            $dataModelOfAttribute = $modelForm->getDataModelByNameAttribute($curNameAttribute);

            switch($dataModelOfAttribute['type_widget']) {
                case 'hidden':

                    echo $form->field($modelForm, $curNameAttribute)->hiddenInput()->label(false);

                    break;

                case 'textfield':

                    echo $form->field($modelForm, $curNameAttribute)->textInput();

                    break;

                case 'datepicker':

                    echo  $form->field($modelForm, $curNameAttribute)->widget(DatePicker::classname(), [
                        //'language' => 'ru',
                        'dateFormat' => 'php:d.m.Y',
                        'options'=>['class'=>'form-control']
                    ]);

                    //$form->field($modelForm, $curNameAttribute)->textInput()->label($dataModelOfAttribute['label']);

                    break;

            }

        }


    }

    ?>


    <div class="form-group">
        <?= Html::submitButton('Создать', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>


</div>

views/basematerial/import.php
<?php
use yii\widgets\ActiveForm;

$this->title = 'Импорт данных';
$this->params['breadcrumbs'][] = $this->title;
$script = <<< JS
function isDublicate(arr)
{
    for (var i = 0; i < arr.length; i++)
    {
        for (var j = 0; j < arr.length; j++)
        {
            if ((arr[i] == arr[j]) && (i != j) && (arr[i] != '') && (arr[j] != ''))
               return true;
        }
    }
    return false;
}
function isInArray(arr, el)
{
    for (var i=0; i < arr.length; i++)
    {
        if (arr[i] == el)
        return true;
    }
    return false;
}
$('form button[type=submit]').click(function(){
    var arrColumns = [];
    var i = 0;
    $('select').each(function()
    {
        arrColumns[i] = $(this).val();
        i++;
    });
    $('.alert-danger').addClass('hidden');
    if (arrColumns[0] == '')
    {
        $('.alert-danger').removeClass('hidden');
        $('.alert-danger').text('Выберите колонку соответствующую наименованию');
        return false;
    }
    if (isDublicate(arrColumns))
    {
        $('.alert-danger').removeClass('hidden');
        $('.alert-danger').text('Колонки не могут повторяться');
        return false;
    }
    return true;
});

JS;

$this->registerJs($script, yii\web\View::POS_READY);
$this->registerCss("
.columnName {

}
");
?>

<h3><? echo 'Импорт для группы '.$catalog->name?></h3>
<div class="row">
    <?
    $formList = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);
    ?>
    <div class="col-xs-12">
    <? echo $formList->field($importModel, 'file')->fileInput();?>
    </div>
    <div class="col-xs-8">
        <table class="table table-bordered table-striped">
            <tr><td><b>Характеристика</b></td><td><b>Соотвествующее имя столбца в Excel</b></td></tr>
        <?
        foreach ($importModel->columnSettings as $currentColumnSetting)
        {
            ?>
                <tr>
                    <td>
                        <?
                            echo $currentColumnSetting['label'];
                            echo \yii\helpers\Html::hiddenInput('ImportModel[columnSettings]['.$currentColumnSetting['name'].'][name]', $currentColumnSetting['name']);
                            echo \yii\helpers\Html::hiddenInput('ImportModel[columnSettings]['.$currentColumnSetting['name'].'][label]', $currentColumnSetting['label']);
                        ?>
                    </td>
                    <td>
                         <?
                            echo \yii\helpers\Html::dropDownList('ImportModel[columnSettings]['.$currentColumnSetting['name'].'][nameExcelColumn]',
                            $currentColumnSetting['nameExcelColumn'], \app\models\ImportModel::$columnNamesExcel,
                                    ['prompt' => 'Выберите колонку', 'class'=>'form-control']);
                         ?>
                    </td>
                </tr>
            <?
        }
        ?>
        </table>
<!--        --><?// echo $formList->field($importModel, 'startRow') ?>
        <div class="alert alert-danger hidden">

        </div>
        <button type="submit" class="btn btn-primary">Импортировать</button>
    </div>
    <? ActiveForm::end() ?>
</div>

views/basematerial/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\helpers\Url;
use app\models\DynamicFormMaterial;
/* @var $this yii\web\View */
/* @var $searchModel app\models\BaseMaterialSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = $group_name;//'Материалы группы1 ';
$this->params['breadcrumbs'][] = $this->title;
$url = Url::toRoute(['/basematerial/model', 'id' => $group_id]);
$urlUpdate = Url::toRoute(['/basematerial/update']);
$script = <<< JS
var idMaterial;
$('.listitem').click(function(){
    idMaterial = $(this).attr('id');
    var x = $.ajax({
        'url' : '{$url}'+'&material_id='+idMaterial
    }).done(function()
    {
        console.log(x);
        $("#detailview").empty();
        $("#detailview").append(x.responseText)
        $("#material").removeClass("hidden");
    });
    console.log(x);
})
$("#material").click(function(){
    var url = '{$urlUpdate}'+'?id='+idMaterial+'&group_id='+'{$group_id}';
    console.log('material click');
    $(location).attr('href', url);
})
JS;

$this->registerJs($script, yii\web\View::POS_READY);
?>
<div class="base-material2-index">

    <h3><?
        echo Html::encode($this->title);
//        if ($group_name)
//            echo $group_name;
        ?>
    </h3>
    <p>
        <?= Html::a('Назад в каталог', ['/catalog/index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Добавить материал', ['/basematerial/create', 'id' => $group_id], ['class' => 'btn btn-primary']) ?>
    </p>
    <div class="col-xs-3">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => function ($model) {
                return Html::tag('button', $model->name, ['type' => 'button', 'class' => 'btn btn-sm btn-default listitem', 'id' => $model->id, 'style'=>'width:100%;text-align: left']);
            }
        ]); ?>
    </div>
    <div class="col-xs-6">
        <div id="detailview"></div>
        <button class="btn btn-success hidden" id="material">Редактировать</button>
    </div>
</div>

views/basematerial/search.php
<?php
use yii\widgets\ActiveForm;

$script = <<< JS
$('#clearfilter').click(function(){
    $('input:not(:hidden)').each(function(){
        $(this).val('')
    });
    $('select').val('');
    $('#search').trigger("click");
})
JS;
$this->registerJs($script);
?>
<?
$form = ActiveForm::begin();
if ($model->columnSettings)
foreach ($model->columnSettings as $currentColumnSetting)
{
    echo '<div>'.$currentColumnSetting['name'].'</div>';
    if ($currentColumnSetting['type_value'] == 1)
    {
        echo \yii\helpers\Html::hiddenInput(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][name]',
            $currentColumnSetting['name']);
        echo \yii\helpers\Html::hiddenInput(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][label]',
            $currentColumnSetting['label']);
        echo \yii\helpers\Html::textInput(
                'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][value]',
                $currentColumnSetting['value'], ["class" => "form-control"]).'<br>';
        echo \yii\helpers\Html::hiddenInput(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][type_value]',
            $currentColumnSetting['type_value']);
    }
    else
    {
        echo \yii\helpers\Html::hiddenInput(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][name]',
            $currentColumnSetting['name']);
        echo \yii\helpers\Html::hiddenInput(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][label]',
            $currentColumnSetting['label']);
        echo \yii\helpers\Html::dropDownList(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][firstcompare]',
            $currentColumnSetting['firstcompare'],
            \app\models\DynamicMaterialFormSearch::$comparasion,
            ['prompt' => '', "class" => "form-control", "style" => "width:15%"]
            );
        echo \yii\helpers\Html::textInput(
                'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][firstvalue]',
                $currentColumnSetting['firstvalue'],
                [
                    "class" => "form-control",
                    "style" => "width:35%"
                ]);
        //echo $currentColumnSetting['label']['firstvalue'];
        echo \yii\helpers\Html::dropDownList(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][secondcompare]',
            $currentColumnSetting['secondcompare'
            ],
            \app\models\DynamicMaterialFormSearch::$comparasion,
            ['prompt' => '', "class" => "form-control", "style" => "width:15%"]
        );
        echo \yii\helpers\Html::textInput(
                'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][secondvalue]',
                $currentColumnSetting['secondvalue'],
                [
                    "class" => "form-control",
                    "style" => "width:35%"
                ]).'<br>';
        echo \yii\helpers\Html::hiddenInput(
            'DynamicMaterialFormSearch[columnSettings]['.$currentColumnSetting['label'].'][type_value]',
            $currentColumnSetting['type_value']);
    }
}
else
    echo '<p>Нет данных группы</p>'
?>
<br>
<button type="submit" id="search" class="btn btn-primary">Применить фильтр</button>
<button type="button" id="clearfilter" class="btn btn-warning">Очистить фильтр</button>

<?
ActiveForm::end() ?>

views/basematerial/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use yii\base\DynamicModel;

/* @var $this yii\web\View */
/* @var $model app\models\BaseMaterial2 */

$this->title = 'Редактирование материала';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="base-material2-update">
    <h3><?= Html::encode($this->title).": ".$modelForm->name; ?></h3>

    <?php $form = ActiveForm::begin(); ?>

    <?php

        foreach ($modelForm->attributes() as $curNameAttribute) {

            if(isset($modelForm->$curNameAttribute)) {

                $valueAttribute = $modelForm->$curNameAttribute;
                $dataModelOfAttribute = $modelForm->getDataModelByNameAttribute($curNameAttribute);

                switch($dataModelOfAttribute['type_widget']) {
                    case 'hidden':

                        echo $form->field($modelForm, $curNameAttribute)->hiddenInput()->label(false);

                    break;

                    case 'textfield':

                        echo $form->field($modelForm, $curNameAttribute)->textInput();

                    break;

                    case 'datepicker':

                        echo  $form->field($modelForm, $curNameAttribute)->widget(DatePicker::classname(), [
                            //'language' => 'ru',
                            'dateFormat' => 'php:d.m.Y',
                            'options'=>['class'=>'form-control']
                        ]);

                       //$form->field($modelForm, $curNameAttribute)->textInput()->label($dataModelOfAttribute['label']);

                    break;

                }

            }


        }

    ?>


    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>


</div>

views/basematerial/userindex.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\helpers\Url;
use \yii\bootstrap\Modal;


$this->title = $group_name;//'Материалы группы1 ';
$this->params['breadcrumbs'][] = $this->title;
$url = Url::toRoute(['/basematerial/model', 'id' => $group_id]);
$urlReport = Url::toRoute(['basematerial/addreport']);
$urlGetExcel = Url::toRoute(['basematerial/getreportexcel']);
$css = <<< CSS
.form-control{
    display:inline;
}
CSS;

$script = <<< JS
var idMaterial;
$('.listitem').click(function(){
    idMaterial = $(this).attr('id');
    var x = $.ajax({
        'url' : '{$url}'+'&material_id='+idMaterial
    }).done(function()
    {
        $("#detailview").empty();
        $("#detailview").append(x.responseText);
        $("#buttonlist").removeClass("hidden");
        $("#resultmessage").addClass("hidden");
    });
})
$("#getExcelReport").click(function(){
    var x = $.ajax({
        'url' : '{$urlGetExcel}'
    }).done(function(){
        console.log(x);
        if (x.responseText != 'false')
            window.open(JSON.parse(x.responseText), '_self')
        else
            alert('Не добавлены материалы в отчет')
    })
})
$("#report").click(function(){
    var x = $.ajax({
        'url' : '{$urlReport}'+'?id='+idMaterial+'&group_id='+'{$group_id}'
    }).done(function()
    {
        console.log(x);
        $("#resultmessage").empty();
        $("#resultmessage").append(x.responseText);
        $("#resultmessage").removeClass("hidden");;
    });
})
JS;
$this->registerCss($css);
$this->registerJs($script, yii\web\View::POS_READY);
?>
<? if (!$message) {?>
<div class="base-material2-index">

    <h3><?
        echo Html::encode($this->title);
//        if ($group_name)
//            echo $group_name;
        ?>
    </h3>
    <div>
        <?= Html::a('Назад в каталог', ['/catalog/index'], ['class' => 'btn btn-primary']) ?>


        <button id="getExcelReport" class="btn btn-primary">
            Сгенерировать отчет
        </button>
<!--        --><?//= Html::a('Сгенерировать отчет', ['/basematerial/report'], ['class' => 'btn btn-primary']) ?>

        <?
        if ($model)
        {
        Modal::begin([
            'header' => '<h4> Поиск по фильтру </h4>',
            'toggleButton' => ['label' => 'Фильтр','class' => 'btn btn-primary']
        ]);
        echo
        $this->render('search',
            [
                'model' => $model
            ]);
        Modal::end();
        }?>
    </div>
    <br>
    <div class="col-xs-3">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => function ($model) {
                return Html::tag(
                    'button',
                    $model->name,
                    [
                        'type' => 'button',
                        'class' => 'btn btn-sm btn-default listitem',
                        'id' => $model->id,
                        'style'=>'width:200px;text-align: left'
                    ]);
            }
        ]); ?>
    </div>
    <div class="col-xs-9">
        <div id="detailview"></div>
        <div id="buttonlist" class="hidden">
            <button class="btn btn-success" id="report">Добавить в отчет</button>
        </div>
        <br>
        <div>
        <div id="resultmessage" style="height:80px">

        </div>
    </div>
</div>
<? }
else
{
    ?>
    <p>
        <?= Html::a('Назад в каталог', ['/catalog/index'], ['class' => 'btn btn-primary']) ?>
    </p>
    <?
        echo '<h4>'.$message.'</h4>';
};
    ?>

views/basematerial/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\BaseMaterial2 */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Base Material2s', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="base-material2-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'date_verify',
            'source',
            'code',
            'note',
        ],
    ]) ?>

</div>